// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package orm

import (
	"database/sql"
)

type Listen struct {
	ListenID         int32          `json:"listen_id"`
	SpotifyID        sql.NullString `json:"spotify_id"`
	SpotifyHref      sql.NullString `json:"spotify_href"`
	SpotifyUri       sql.NullString `json:"spotify_uri"`
	Artist           sql.NullString `json:"artist"`
	ArtistGenres     sql.NullString `json:"artist_genres"`
	TrackName        sql.NullString `json:"track_name"`
	AlbumName        sql.NullString `json:"album_name"`
	AlbumImage       sql.NullString `json:"album_image"`
	AlbumImageHeight sql.NullInt32  `json:"album_image_height"`
	AlbumImageWidth  sql.NullInt32  `json:"album_image_width"`
	Html             sql.NullString `json:"html"`
	ListenedAt       sql.NullTime   `json:"listened_at"`
}
